### ISSUE TITLE
PyETo is missing from PyPI

### ISSUE THREAD

**Issue by SHuizer** [woodcrafty/PyETo#3]
When I try to install the package via pip, I get a 'No matching distribution found for pyeto" error, and when I look for the package in PyPI (https://pypi.python.org/pypi) I can not find it.

**Comment by woodcrafty** [comment]
Hi, Thanks for your interest. I have not put the package on PyPI yet. I wanted to improve the documentation before I did that. I haven't had much spare time to spend on PyETO for quite a while, so I suggest you download the source from GitHub if you want to use it.
Regards,
Mark

**Comment by SHuizer** [comment]
Hi, thanks for your quick reply. I will download the source from Github.

**Comment by bvdscheer** [comment]
Is this still an issue? I cannot install using 'pip install pyeto'.

**Comment by divyadeySk** [comment]
Cannot install the package using 'pip install pyeto'
![image](https://user-images.githubusercontent.com/85478071/120970978-c2f1b700-c789-11eb-9610-a191b02f32df.png)

**Comment by kdl0013** [comment]
The creator will not upload the package to PyPi but also will not take it down from the webpage saying that is on PyPi. https://pyeto.readthedocs.io/en/latest/overview.html. It's been 5 years, take it off the website.
