### ISSUE TITLE
Is there any provision to calculate ET for another crops if we know the crop coefficient data?

### ISSUE THREAD

**Issue by kothawadegs** [woodcrafty/PyETo#5]
As PyETo is written for calculation of reference evapotranspiration from a hypothetical grass reference surface, the calculations for the other crops would be different. How can we compute the reference evapotranspiration from the Winter Crops, if we know the crop coefficient Kc for the respective crops?

**Comment by brycejohnston** [comment]
To get potential evapotranspiration you would take the crop coefficient for the particular growth stage of that crop multiplied by the reference evapotranspiration you get from the FAO equations (hypothetical grass)

PET = Kc * Ref ET

**Comment by kothawadegs** [comment]
@beaorn Yes, it's mentioned in FAO 56 paper. Thanks for the answer.
